stages:
  - sync

sync-gitee:
  stage: sync
  image: bitnami/git:2.40.1
  script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_NAME
    - git config --global user.email
    - git config --global user.name
    - echo 当前分支：$CI_COMMIT_BRANCH
    - git checkout -b $CI_COMMIT_BRANCH
    - git remote add gitee https://gitee.com/xuxiaowei-com-cn/git-sync.git
    - git config --global credential.helper store
    - git config --global credential.https://gitee.com.username xuxiaowei-com-cn
    - git config --global credential.https://gitee.com.password $GITEE_PRIVATE_TOKEN
    - git push -u gitee $CI_COMMIT_BRANCH
  rules:
    # 非 PR 时触发
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == null

sync-gitcode:
  stage: sync
  image: bitnami/git:2.40.1
  script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_NAME
    - git config --global user.email
    - git config --global user.name
    - echo 当前分支：$CI_COMMIT_BRANCH
    - git checkout -b $CI_COMMIT_BRANCH
    - git remote add gitcode https://gitcode.net/xuxiaowei-com-cn/git-sync.git
    - git config --global credential.helper store
    - git config --global credential.https://gitcode.net.username qq_32596527
    - git config --global credential.https://gitcode.net.password $GITCODE_PRIVATE_TOKEN
    - git push -u gitcode $CI_COMMIT_BRANCH
  rules:
    # 非 PR 时触发
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == null

sync-github:
  stage: sync
  image: bitnami/git:2.40.1
  script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_NAME
    - git config --global user.email
    - git config --global user.name
    - echo 当前分支：$CI_COMMIT_BRANCH
    - git checkout -b $CI_COMMIT_BRANCH
    - git remote add github https://$GITHUB_PRIVATE_TOKEN@github.com/xuxiaowei-com-cn/git-sync.git
    - git push -u github $CI_COMMIT_BRANCH
  rules:
    # 非 PR 时触发
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == null
  retry: 2
